"use client";

import { useEffect, useMemo, useState } from "react";

type Tab = "oggi" | "fondamentali" | "diagrammi" | "esame";
type Topic = { id:string; title:string; area:string; icon:string; use:string; keys:string[]; technique:string[]; tactics:string; errors:string[]; exam:string };

const coreTopics: Topic[] = [
  {id:"uncino",title:"Tiro ad uncino / semigancio",area:"Tiro",icon:"◔",use:"Concludere vicino a canestro proteggendo la palla dal difensore con il corpo.",keys:["Piede opposto alla mano di tiro verso canestro","Palla lontana dal difensore, vicina all’orecchio","Distensione del braccio e frustata di polso e dita"],technique:["La mano di tiro passa sotto la palla mentre sale.","La mano guida resta laterale e accompagna fino al rilascio.","La spalla opposta alla mano di tiro è rivolta al petto del difensore.","In chiusura: palmo della mano di tiro verso il suolo, braccia alte e caduta in equilibrio."],tactics:"Si usa vicino a canestro quando occorre tirare tenendo la palla lontana dal difensore.",errors:["Portare la palla davanti al difensore","Non usare il corpo come protezione","Cadere all’indietro o fuori equilibrio"],exam:"Il tiro ad uncino, chiamato spesso semigancio, è una conclusione ravvicinata che protegge la palla con il corpo. Si avanza con il piede opposto alla mano di tiro, portando la palla vicino all’orecchio e lontano dal difensore. La mano passa sotto la palla, il braccio si distende e il gesto termina con la frustata del polso e delle dita. La mano guida accompagna fino al rilascio e la caduta deve essere equilibrata."},
  {id:"palleggio",title:"Palleggio",area:"Attacco",icon:"●",use:"Spostarsi con la palla, creare vantaggio e migliorare una linea di passaggio.",keys:["Spinta con polso e dita","Testa alta e visione del gioco","Palla protetta e controllo del corpo"],technique:["Mano sopra e leggermente dietro la palla.","Spinta elastica con polso e dita, senza schiaffeggiare.","Altezza e distanza cambiano secondo velocità, spazio e difensore."],tactics:"Il palleggio è un mezzo, non il fine: serve a creare vantaggio o risolvere una situazione.",errors:["Guardare continuamente la palla","Palleggiare senza obiettivo","Palla esposta al difensore"],exam:"Il palleggio permette di muoversi con la palla. Tecnicamente si controlla con polso e dita, mantenendo equilibrio e visione del gioco. Tatticamente deve avere uno scopo: creare vantaggio, superare pressione o aprire una linea di passaggio."},
  {id:"cambio",title:"Cambio frontale incrociato e omologo",area:"Palleggio",icon:"↔",use:"Cambiare direzione leggendo spazio e distanza dal difensore.",keys:["Cambio basso sotto le ginocchia","Avviene prima dell’ostacolo o difensore","Accelerazione immediata dopo il cambio"],technique:["Incrociato: il piede opposto alla nuova mano attacca lo spazio.","Omologo: il piede dello stesso lato della nuova mano anticipa l’uscita.","La mano passa da sopra a sopra-laterale della palla."],tactics:"Difensore vicino: privilegiare l’incrociato. Spazio maggiore o difensore lontano: l’omologo consente di anticipare l’uscita.",errors:["Cambio troppo alto","Cambio eseguito sotto o dopo il difensore","Nessuna accelerazione in uscita"],exam:"Il cambio di mano frontale permette di cambiare direzione davanti al corpo. Si prepara con palleggio controllato, si esegue basso e prima del difensore, quindi si accelera. La scelta tra incrociato e omologo dipende soprattutto dalla distanza e dallo spazio disponibile."},
  {id:"passaggio",title:"Passaggio",area:"Attacco",icon:"⇢",use:"Far arrivare la palla al punto giusto nel momento giusto e mantenere il vantaggio.",keys:["Leggere la linea aperta","Precisione e tempo corretto","Collaborazione tra passatore e ricevente"],technique:["Equilibrio e presa sicura.","Spinta coordinata di gambe, braccia, polsi e dita.","Il tipo di passaggio dipende dalla linea disponibile."],tactics:"Petto, schiacciato, sopra la testa, laterale, baseball, consegnato o da palleggio si scelgono leggendo spazio e difesa.",errors:["Passaggio lento o telefonato","Non guardare il difensore","Ricevente fermo senza mostrare un bersaglio"],exam:"Il passaggio serve a mantenere il vantaggio facendo arrivare la palla al punto giusto nel momento giusto. Tecnica e scelta non sono separate: il giocatore usa il passaggio adatto alla linea lasciata libera dalla difesa."},
  {id:"tiro",title:"Tiro",area:"Attacco",icon:"⌁",use:"Concretizzare il vantaggio con una conclusione ad alta percentuale.",keys:["Equilibrio","Allineamento","Continuità e frustata finale"],technique:["Piedi e corpo in equilibrio.","Mano di tiro sotto la palla, mano guida laterale.","Distensione coordinata e chiusura del polso verso il canestro."],tactics:"La scelta dipende da spazio, tempo, distanza e posizione del difensore.",errors:["Gomito aperto senza controllo","Mano guida che spinge","Interruzione della catena gambe-braccio-polso"],exam:"Il tiro è il fondamentale con cui si concretizza il vantaggio. Richiede equilibrio, coordinazione, corretta presa e continuità dalla spinta delle gambe fino alla frustata finale del polso."},
  {id:"difesa",title:"Posizione e difesa sulla palla",area:"Difesa",icon:"◇",use:"Contenere l’attaccante, togliere spazio utile e recuperare la palla.",keys:["Equilibrio e reattività","Distanza adeguata","Petto davanti alla palla"],technique:["Piedi attivi, base stabile e busto pronto.","Scivolare senza incrociare i piedi quando possibile.","Mani attive coerenti con palla e linee di passaggio."],tactics:"La distanza cambia secondo capacità dell’attaccante, posizione della palla e spazio da proteggere.",errors:["Peso sui talloni","Piedi che si uniscono","Cercare la palla perdendo posizione"],exam:"La difesa sulla palla nasce dalla posizione fondamentale e dalla distanza. Il difensore deve rimanere equilibrato, orientare l’attaccante e mantenere il petto davanti alla palla, usando piedi e mani in modo coordinato."}
];

const mk=(id:string,title:string,area:string,icon:string,use:string,keys:string[],technique:string[],tactics:string,errors:string[]):Topic=>({id,title,area,icon,use,keys,technique,tactics,errors,exam:`${title}: ${use} Gli elementi tecnici essenziali sono: ${technique.join(" ")} Dal punto di vista tattico, ${tactics.charAt(0).toLowerCase()+tactics.slice(1)}`});
const extraTopics:Topic[]=[
 mk("posizione-off","Posizione fondamentale offensiva","Senza palla","△","Preparare ogni movimento offensivo mantenendo equilibrio e possibilità di scelta.",["Piedi alla larghezza delle spalle","Gambe piegate e peso sull’avampiede","Testa alta e corpo pronto"],["Base stabile ma non rigida.","Ginocchia e caviglie piegate.","Tronco leggermente inclinato e mani pronte."],"è la posizione di partenza per ricevere, passare, tirare, partire o cambiare direzione.",["Gambe tese","Peso sui talloni","Sguardo basso"]),
 mk("presa","Presa e ricezione della palla","Attacco","◉","Controllare immediatamente la palla ed essere pronti alla scelta successiva.",["Mani pronte e bersaglio","Ammortizzare la ricezione","Palla protetta e visione"],["Dita aperte e pollici orientati secondo la traiettoria.","Le braccia accompagnano la palla verso il corpo.","Dopo la presa si recuperano equilibrio e posizione fondamentale."],"la ricezione deve avvenire nel tempo e nello spazio utili, già orientati verso il gioco.",["Aspettare la palla con mani basse","Corpo rigido","Guardare solo la palla"]),
 mk("arresto-uno","Arresto ad un tempo","Senza palla","▣","Fermare il movimento atterrando contemporaneamente sui due piedi.",["Stacco controllato","Appoggio simultaneo","Equilibrio e libertà di perno"],["Breve fase di volo.","I piedi arrivano contemporaneamente a terra.","Caviglie, ginocchia e anche ammortizzano l’impatto."],"consente di scegliere il piede perno e risulta utile quando serve equilibrio immediato.",["Atterrare rigidi","Piedi troppo stretti","Perdere il controllo in avanti"]),
 mk("arresto-due","Arresto a due tempi","Senza palla","Ⅱ","Fermare la corsa con due appoggi successivi e controllati.",["Primo appoggio frena","Secondo appoggio equilibra","Il primo piede diventa perno"],["Gli appoggi avvengono in successione.","Il baricentro si abbassa durante la frenata.","Il corpo termina stabile e orientato."],"si usa per adattare l’arresto a traiettoria, velocità e spazio disponibile.",["Appoggi troppo lunghi","Baricentro alto","Confondere il piede perno"]),
 mk("perno","Piede perno e giro","Senza palla","↻","Proteggere la palla e cambiare orientamento senza commettere passi.",["Perno stabile","Passi brevi con il piede libero","Palla protetta e testa alta"],["Il piede perno mantiene il contatto con il terreno.","Il corpo ruota in equilibrio.","La palla resta lontana dalla pressione difensiva."],"serve a creare una linea di passaggio, tiro o partenza e a proteggere il possesso.",["Spostare il perno","Ruotare senza vedere il campo","Esporre la palla"]),
 mk("partenza-inc","Partenza incrociata","Partenze","⤢","Battere il difensore attaccando lo spazio con il piede opposto alla direzione.",["Palla e piede partono insieme","Passo incrociato oltre il difensore","Spalla bassa e accelerazione"],["Il piede opposto incrocia davanti al corpo.","La palla viene messa a terra prima che il perno si sollevi.","Il primo passo conquista spazio utile."],"è efficace quando il difensore è vicino e occorre proteggere la palla con il corpo.",["Alzare il perno prima del palleggio","Primo passo laterale","Palla esposta"]),
 mk("partenza-omo","Partenza omologa","Partenze","⤡","Attaccare rapidamente lo spazio sullo stesso lato del piede di partenza.",["Piede omologo nella direzione","Palla a terra nel tempo corretto","Accelerazione nello spazio"],["Il piede dello stesso lato apre la traiettoria.","Il palleggio precede il distacco del piede perno.","Corpo e palla avanzano protetti."],"si privilegia quando lo spazio è maggiore e la pressione del difensore consente l’uscita diretta.",["Infrazione di passi","Passo corto senza vantaggio","Nessun cambio di velocità"]),
 mk("palleggio-protetto","Palleggio protetto","Palleggio","◐","Mantenere il possesso quando il difensore esercita pressione.",["Palla lontana dal difensore","Altezza del ginocchio","Corpo e braccio libero proteggono"],["Posizione fondamentale bassa.","Palleggio laterale e controllato.","Mano sopra-laterale e contatto breve con la palla."],"si usa sotto pressione, senza perdere la visione delle linee di passaggio.",["Palleggio alto","Palla davanti ai piedi","Spingere il difensore col braccio"]),
 mk("palleggio-spinto","Palleggio spinto","Palleggio","➤","Percorrere spazio in velocità mantenendo controllo e visione.",["Palla spinta avanti","Altezza circa alla cintola","Corsa e palleggio coordinati"],["La mano lavora dietro e sopra la palla.","Il rimbalzo è davanti al corpo.","La frequenza si adatta alla velocità di corsa."],"si usa in campo aperto, contropiede o quando non c’è pressione ravvicinata.",["Palla troppo vicina ai piedi","Guardare in basso","Spingere la palla troppo lontano"]),
 mk("palleggio-alternato","Palleggio spinto alternato","Palleggio","⇆","Avanzare rapidamente alternando le mani secondo traiettoria e pressione.",["Cambio continuo di mano","Palla davanti al corpo","Ritmo coordinato con la corsa"],["Ogni spinta manda la palla verso la mano opposta.","Il busto resta orientato in avanti.","La palla viene controllata all’altezza utile alla velocità."],"offre velocità e adattamento in spazi aperti, leggendo eventuali difensori.",["Cambio troppo largo","Perdita del ritmo","Sguardo sulla palla"]),
 mk("cambio-velocita","Cambio di velocità in palleggio","Palleggio","⚡","Creare vantaggio modificando improvvisamente ritmo e velocità.",["Rallentamento credibile","Lettura della reazione","Ripartenza esplosiva"],["Il palleggio rallenta e può alzarsi leggermente.","Il corpo simula una pausa o un arresto.","La ripartenza avviene con passo lungo e palleggio spinto."],"serve a sbilanciare un difensore che sta controllando la stessa velocità.",["Rallentamento assente","Ripartenza senza accelerazione","Perdere protezione"]),
 mk("dietro-schiena","Cambio di mano dietro schiena","Palleggio","↩","Cambiare direzione proteggendo la palla quando il difensore occupa lo spazio frontale.",["Palla spinta dietro il corpo","Ricezione con mano opposta","Cambio di direzione e velocità"],["Il palleggio parte lateralmente e passa dietro il bacino.","La mano opposta riceve senza cercare la palla.","Piedi e busto preparano la nuova direzione."],"si usa quando lo spazio davanti è chiuso e portare la palla frontalmente sarebbe rischioso.",["Palla troppo lontana","Cambio dietro i talloni","Nessuna uscita in velocità"]),
 mk("sotto-gambe","Cambio di mano sotto le gambe","Palleggio","⌁","Cambiare direzione mantenendo la palla protetta nello spazio tra le gambe.",["Gambe sfalsate e piegate","Palla bassa sotto il corpo","Ricezione e spinta opposta"],["Una gamba avanza creando il canale.","La palla attraversa sotto il bacino.","Il peso si trasferisce verso la nuova direzione."],"è utile sotto pressione perché il corpo protegge la traiettoria della palla.",["Gambe rigide","Rimbalzo troppo alto","Palla che colpisce il piede"]),
 mk("virata","Giro in palleggio o virata","Palleggio","⟳","Superare una pressione ravvicinata ruotando e proteggendo la palla.",["Arresto controllato","Perno e dorso al difensore","Uscita con mano opposta"],["Si appoggia il piede interno come perno.","Il corpo ruota proteggendo la palla.","Il palleggio cambia mano e riparte nella nuova direzione."],"si usa quando il difensore chiude lateralmente ed è molto vicino.",["Rotazione lenta","Palla esposta durante il giro","Uscita senza vedere il campo"]),
 mk("pass-petto","Passaggio due mani dal petto","Passaggio","⇉","Servire rapidamente un compagno su una linea diretta aperta.",["Palla davanti al petto","Spinta di gambe, braccia e polsi","Frustata finale e passo"],["Mani dietro la palla e gomiti naturalmente stretti.","Braccia distese verso il bersaglio.","Pollici, indici e medi completano la spinta."],"si usa su linea diretta, spesso in contropiede o contro una difesa a zona.",["Gomiti larghi","Palla lenta ad arco","Passo fuori direzione"]),
 mk("pass-schiacciato","Passaggio due mani schiacciato","Passaggio","↘","Superare braccia o pressione usando la linea bassa.",["Partenza dalla cintola","Rimbalzo circa a due terzi","Ricezione all’altezza utile"],["Tecnica simile al passaggio dal petto.","La spinta è orientata verso il terreno.","La traiettoria deve restare tesa e prevedibile per il compagno."],"si usa quando la linea aerea è chiusa e c’è spazio vicino al terreno.",["Rimbalzo troppo vicino","Passaggio molle","Usarlo con difensore a contatto sulla linea bassa"]),
 mk("pass-testa","Passaggio sopra la testa","Passaggio","⇈","Utilizzare una linea di passaggio alta sopra difensori o pressione.",["Palla sopra la fronte","Gomiti sotto la palla","Spinta di mani e polsi"],["Le braccia si distendono verso il ricevente.","I polsi e le dita danno direzione.","Un piccolo passo accompagna il passaggio."],"si usa quando la linea libera è sopra la testa o sopra le spalle.",["Portare la palla dietro la testa","Passaggio a parabola lenta","Gomiti troppo aperti"]),
 mk("pass-laterale","Passaggio laterale a una o due mani","Passaggio","↝","Aggirare il difensore aprendo una linea laterale.",["Perno ed equilibrio","Palla fuori dalla sagoma difensiva","Polso orientato al bersaglio"],["Il corpo crea una finestra laterale.","Il braccio distende senza perdere controllo.","Il passo e il passaggio sono coordinati."],"si sceglie quando il difensore chiude la linea centrale ma lascia spazio laterale.",["Sbilanciarsi","Telegrafare la direzione","Palla esposta prima del rilascio"]),
 mk("pass-baseball","Passaggio baseball","Passaggio","➶","Coprire una grande distanza con rapidità e precisione.",["Palla vicino alla spalla","Rotazione coordinata del corpo","Traiettoria tesa verso lo spazio"],["Presa salda con mano di spinta e guida iniziale.","Gambe e tronco producono forza.","Il braccio completa il movimento verso il bersaglio."],"si usa soprattutto per apertura lunga e contropiede.",["Solo forza del braccio","Traiettoria alta e lenta","Bersaglio fermo invece dello spazio"]),
 mk("pass-consegnato","Passaggio consegnato","Passaggio","⇄","Trasferire la palla a un compagno vicino mantenendo protezione e continuità.",["Palla protetta","Compagno passa vicino","Consegna nel tempo corretto"],["Il portatore presenta la palla sul lato protetto.","Il ricevente entra vicino e prende con due mani.","Corpi e traiettorie limitano l’intervento difensivo."],"può creare un cambio di lato, una penetrazione o una collaborazione simile a un blocco.",["Palla lontana dal corpo","Distanza eccessiva","Consegna senza leggere il difensore"]),
 mk("pass-palleggio","Passaggio da palleggio","Passaggio","➠","Ridurre il tempo tra ultimo palleggio e passaggio, mantenendo il vantaggio.",["Lettura prima della raccolta","Spinta diretta dal palleggio","Precisione con una mano"],["La mano accompagna la palla dal rimbalzo al passaggio.","Il gesto evita una presa intermedia lenta.","Corpo e piedi restano orientati alla scelta."],"si usa quando il tempo disponibile è minimo e la linea si apre durante il palleggio.",["Fermare inutilmente la palla","Passaggio senza equilibrio","Mano debole non allenata"]),
 mk("finte","Finte con e senza palla","Attacco","≈","Provocare una reazione difensiva per aprire spazio o tempo vantaggioso.",["Gesto credibile","Leggere la risposta","Attaccare subito il vantaggio"],["Occhi, palla, piedi e corpo comunicano un’intenzione.","L’ampiezza è sufficiente a provocare risposta, non eccessiva.","La seconda azione parte senza pausa."],"una finta è utile solo se collegata alla lettura e a un’azione successiva efficace.",["Finta troppo grande","Guardare già la seconda scelta","Nessuna accelerazione dopo la reazione"]),
 mk("tiro-fermo","Tiro da fermo","Tiro","⌂","Concludere in equilibrio senza elevazione significativa.",["Piedi equilibrati","Presa e allineamento","Distensione e frustata"],["Le gambe iniziano la spinta.","Mano di tiro sotto la palla e guida laterale.","Braccio e polso terminano verso il canestro."],"è la base tecnica del tiro e si usa quando tempo e spazio consentono stabilità.",["Spinta solo di braccia","Mano guida attiva","Mancanza di equilibrio"]),
 mk("tiro-elevazione","Tiro in elevazione","Tiro","⇧","Tirare salendo verticalmente per aumentare altezza e protezione del rilascio.",["Salita verticale","Palla pronta durante l’elevazione","Rilascio coordinato"],["La spinta delle gambe solleva il corpo.","La palla sale nella posizione di tiro.","Il rilascio avviene durante la salita con caduta equilibrata."],"si usa quando serve alzare il punto di rilascio senza perdere continuità.",["Saltare in avanti senza controllo","Palla che sale tardi","Caduta fuori equilibrio"]),
 mk("tiro-sospensione","Tiro in sospensione","Tiro","⇡","Creare separazione e rilasciare la palla vicino al punto alto del salto.",["Arresto equilibrato","Elevazione controllata","Rilascio al punto utile"],["Il corpo sale verticale.","La palla resta allineata alla mano di tiro.","Il gesto si completa prima della ricaduta."],"si utilizza contro una pressione maggiore, scegliendo altezza e tempo rispetto al difensore.",["Rilascio in discesa","Gambe disperse","Forzare senza spazio"]),
 mk("terzo-tempo","Tiro in corsa: terzo tempo","Tiro in corsa","①","Concludere al ferro trasformando la corsa in due appoggi e salto.",["Raccolta nel tempo corretto","Due appoggi coordinati","Salto sul piede opposto alla mano"],["La palla viene raccolta prima dei due appoggi consentiti.","Il ginocchio libero sale proteggendo il gesto.","La mano accompagna la palla al tabellone o al canestro."],"si usa dopo aver creato vantaggio e raggiunto lo spazio vicino al ferro.",["Passi irregolari","Palla bassa durante gli appoggi","Salto senza equilibrio"]),
 mk("secondo-tempo","Tiro in corsa: secondo tempo","Tiro in corsa","②","Concludere rapidamente utilizzando un solo appoggio dopo la raccolta.",["Raccolta anticipata","Un appoggio forte","Rilascio rapido e protetto"],["La palla è controllata prima dell’ultimo appoggio.","Il corpo converte velocità orizzontale in elevazione.","Il rilascio si adatta alla posizione del difensore."],"riduce i tempi e può sorprendere l’aiuto difensivo.",["Raccolta tardiva","Perdita di controllo","Tiro lontano dal corpo"]),
 mk("cambio-dir-omo","Cambio di direzione omologo senza palla","Senza palla","⤴","Cambiare direzione usando come appoggio il piede dello stesso lato della nuova traiettoria.",["Frenata nello spazio","Appoggio omologo","Spinta e accelerazione"],["Il giocatore abbassa il baricentro.","Il piede omologo orienta la nuova direzione.","La ripartenza avviene con cambio di ritmo."],"serve a smarcarsi leggendo spazio, difensore e tempo del passaggio.",["Cambio curvo","Nessuna frenata","Ripartenza lenta"]),
 mk("cambio-dir-inc","Cambio di direzione incrociato senza palla","Senza palla","⤵","Cambiare direzione spingendo sul piede opposto alla nuova traiettoria.",["Frenata e baricentro basso","Spinta sul piede opposto","Taglio netto e accelerazione"],["L’appoggio esterno arresta la prima corsa.","Il corpo ruota verso lo spazio nuovo.","I primi passi successivi sono rapidi."],"si usa per battere il difensore con un taglio netto, soprattutto sotto pressione ravvicinata.",["Passi piccoli prima del cambio","Traiettoria arrotondata","Non mostrare le mani al passatore"]),
 mk("scivolamenti","Scivolamenti difensivi","Difesa","⇔","Mantenere il corpo davanti all’attaccante senza perdere equilibrio.",["Spinta del piede opposto","Piedi non si incrociano","Base stabile e mani attive"],["Il primo piede apre nella direzione.","Il secondo recupera senza unire i piedi.","Il baricentro resta basso e controllato."],"si alternano a corsa e recupero secondo distanza e velocità dell’attaccante.",["Piedi che si toccano","Saltellare","Busto troppo alto"]),
 mk("difesa-no-palla","Difesa sul giocatore senza palla","Difesa","◆","Negare ricezioni vantaggiose mantenendo visione di palla e uomo.",["Posizione rispetto alla palla","Linea di passaggio controllata","Vedere uomo e palla"],["Piede e mano lato palla occupano la linea utile.","Il corpo si orienta secondo distanza e pericolosità.","La posizione cambia mentre la palla si muove."],"può essere più aggressiva o di contenimento, ma deve proteggere tagli e spazi pericolosi.",["Guardare solo la palla","Perdere il contatto visivo con l’uomo","Posizione statica"]),
 mk("linea-passaggio","Linea di passaggio e anticipo","Difesa","╱","Ostacolare o negare il collegamento tra passatore e ricevente.",["Corpo sulla linea utile","Braccio semiflesso attivo","Equilibrio per contenere il taglio"],["Il difensore occupa la linea con piede e mano lato palla.","Il petto è orientato secondo la scelta difensiva.","La distanza consente anticipo senza essere battuti facilmente."],"la pressione sulla linea dipende da posizione della palla, spazio e rischio di taglio back-door.",["Braccio rigido","Corpo completamente girato","Anticipo senza copertura dello spazio dietro"]),
 mk("postulati","Postulati: spazio, tempo, equilibrio, autonomia","Concetti","✦","Leggere il gioco attraverso i riferimenti fondamentali che guidano tecnica e decisioni.",["Spazio utile","Tempo corretto","Equilibrio e autonomia"],["Ogni gesto tecnico è adattato allo spazio disponibile.","La scelta deve avvenire nel tempo che il gioco concede.","Equilibrio permette di eseguire e autonomia permette di decidere."],"i postulati collegano fondamentali tecnici e tattici: guardare, parlare, ascoltare e toccare.",["Insegnare gesti senza situazione","Ignorare tempo e distanza","Dare soluzioni senza responsabilità al giocatore"]),
 mk("vantaggio","Creare, mantenere e concretizzare il vantaggio","Concetti","＋","Organizzare ogni azione offensiva e difensiva attorno al vantaggio.",["Creare spazio o tempo","Mantenere con scelta e collaborazione","Concretizzare con tiro ad alta percentuale"],["Il vantaggio nasce quando un difensore è battuto o impegnato.","Passaggio, palleggio e movimento mantengono il vantaggio.","La conclusione corretta lo trasforma in un risultato."],"in difesa l’obiettivo opposto è togliere il vantaggio, recuperare la palla o forzare un tiro difficile.",["Confondere velocità con vantaggio","Fermare la palla","Concludere senza equilibrio"]),
 mk("progressione","Progressione didattica","Metodologia","▤","Portare il giocatore dal gesto semplice alla lettura e al gioco reale.",["Dal semplice al complesso","Dall’1c0 alla presenza difensiva","Trasferimento in situazione agonistica"],["Si definisce un obiettivo osservabile.","Si costruiscono esercizi coerenti e progressivi.","Regole e difficoltà aumentano senza perdere l’obiettivo."],"la progressione efficace comprende attivazione, fase cognitiva e agonistica, correzione e verifica.",["Esercizi scollegati","Troppe correzioni insieme","Regole che cambiano l’obiettivo"]),
 mk("osservazione","Osservazione e correzione","Metodologia","◎","Vedere ciò che accade realmente e intervenire sull’errore prioritario.",["Osservare rispetto all’obiettivo","Scegliere cosa correggere","Verificare l’effetto della correzione"],["L’allenatore definisce indicatori concreti.","Può correggere direttamente o porre domande.","Lascia tempo al giocatore per adattare la risposta."],"la correzione deve far crescere il singolo e la squadra, senza interrompere inutilmente il gioco.",["Correggere tutto","Osservare la palla soltanto","Dare soluzioni senza domande"])
];
const topics:Topic[]=[...coreTopics,...extraTopics];

const quiz=[{q:"Nel tiro ad uncino, quale piede avanza verso canestro?",a:["Quello opposto alla mano di tiro","Quello della mano di tiro","È indifferente"],ok:0},{q:"Qual è l’obiettivo principale del passaggio?",a:["Evitare il palleggio","Mantenere il vantaggio","Muovere sempre tutti i giocatori"],ok:1},{q:"Quando va effettuato il cambio di mano rispetto al difensore?",a:["Dopo averlo superato","Sotto il suo corpo","Prima, nello spazio utile"],ok:2},{q:"Dopo un cambio di mano efficace cosa deve avvenire?",a:["Una pausa","Un’accelerazione","Un passaggio obbligatorio"],ok:1},{q:"Nell’arresto a due tempi quale piede diventa perno?",a:["Il primo che tocca terra","Il secondo","Entrambi liberamente"],ok:0},{q:"Dove deve rimbalzare il passaggio schiacciato?",a:["A metà esatta","Circa a due terzi verso il ricevente","Vicino al passatore"],ok:1},{q:"Qual è la sequenza didattica più coerente?",a:["3c3, 1c0, spiegazione","1c0, lettura guidata, situazione agonistica","Solo esercizio analitico"],ok:1},{q:"Cosa deve vedere il difensore senza palla?",a:["Solo il proprio uomo","Solo la palla","Uomo e palla"],ok:2},{q:"Quando si privilegia una partenza incrociata?",a:["Difensore vicino e palla da proteggere","Campo completamente libero","Sempre"],ok:0},{q:"A cosa serve una finta?",a:["A rallentare il gioco","A provocare una reazione e attaccarla","A mostrare abilità"],ok:1}];

export default function Home(){
 const[tab,setTab]=useState<Tab>("oggi"),[selected,setSelected]=useState(topics[0]),[reveal,setReveal]=useState(false),[quizIndex,setQuizIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[points,setPoints]=useState(0),[minutes,setMinutes]=useState(30),[running,setRunning]=useState(false),[known,setKnown]=useState<string[]>([]),[search,setSearch]=useState("");
 useEffect(()=>{try{setKnown(JSON.parse(localStorage.getItem("fip-known")||"[]"))}catch{};if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setMinutes(m=>m>0?m-1:0),60000);return()=>clearInterval(id)},[running]);
 const progress=Math.round(known.length/topics.length*100),due=useMemo(()=>topics.filter(t=>!known.includes(t.id)).slice(0,3),[known]),filtered=useMemo(()=>topics.filter(t=>(t.title+" "+t.area).toLowerCase().includes(search.toLowerCase())),[search]);
 const mark=(id:string)=>{const n=known.includes(id)?known.filter(x=>x!==id):[...known,id];setKnown(n);localStorage.setItem("fip-known",JSON.stringify(n))};
 const choose=(i:number)=>{if(answer!==null)return;setAnswer(i);if(i===quiz[quizIndex].ok)setPoints(p=>p+1)};
 return <main><header className="topbar"><div className="brand"><span className="ball">●</span><div><b>FIP MEMORY COACH</b><small>Il tuo allenamento mentale</small></div></div><div className="level">LIVELLO <b>{Math.max(1,known.length)}</b></div></header>
 <nav className="tabs">{([['oggi','Oggi'],['fondamentali','Fondamentali'],['diagrammi','Diagrammi'],['esame','Simula esame']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="oggi"&&<div className="page"><section className="hero"><div><span className="eyebrow">SESSIONE DEL GIORNO · 15 MIN</span><h1>Oggi non rileggi.<br/><em>Oggi ricordi.</em></h1><p>Tre richiami brevi, una spiegazione ad alta voce e un diagramma. Il cervello si allena come il corpo.</p><button className="primary" onClick={()=>{setSelected(due[0]||topics[0]);setTab('fondamentali');setReveal(false)}}>Inizia l’allenamento →</button></div><div className="court-mini"><span className="hoop">◉</span><span className="player p1">1</span><span className="player p2">2</span><span className="route">↗</span><b>{progress}%</b><small>preparazione</small></div></section><section className="statrow"><article><span>ARGOMENTI ACQUISITI</span><b>{known.length}<small>/{topics.length}</small></b></article><article><span>DA RIPASSARE</span><b>{topics.length-known.length}</b></article><article><span>QUIZ DISPONIBILI</span><b>{quiz.length}</b></article></section><h2 className="section-title">I tuoi richiami di oggi</h2><div className="review-grid">{due.length?due.map((t,i)=><button className="review-card" key={t.id} onClick={()=>{setSelected(t);setTab('fondamentali');setReveal(false)}}><span className="num">0{i+1}</span><span className="topic-icon">{t.icon}</span><div><small>{t.area}</small><b>{t.title}</b><p>{i===0?'Richiamo immediato':i===1?'Ripasso guidato':'Spiega ad alta voce'}</p></div><span className="go">→</span></button>):<div className="done">Ottimo lavoro. Hai acquisito tutti i moduli: domani prova a richiamarli di nuovo.</div>}</div></div>}
 {tab==="fondamentali"&&<div className="page split"><aside className="topic-list"><span className="eyebrow">LIBRERIA CNA · {topics.length} MODULI</span><h2>Fondamentali</h2><input className="topic-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca fondamentale…" aria-label="Cerca fondamentale"/>{filtered.map(t=><button key={t.id} onClick={()=>{setSelected(t);setReveal(false)}} className={selected.id===t.id?'active':''}><span>{t.icon}</span><div><small>{t.area}</small>{t.title}</div>{known.includes(t.id)&&<i>✓</i>}</button>)}</aside><section className="lesson"><div className="lesson-head"><div><span className="eyebrow">{selected.area}</span><h1>{selected.title}</h1></div><button className={known.includes(selected.id)?'known active':'known'} onClick={()=>mark(selected.id)}>{known.includes(selected.id)?'✓ Acquisito':'Segna acquisito'}</button></div><div className="purpose"><b>A cosa serve</b><p>{selected.use}</p></div><h3>I 3 ganci della memoria</h3><div className="keys">{selected.keys.map((k,i)=><div key={k}><span>{i+1}</span><p>{k}</p></div>)}</div><div className="recall"><span className="eyebrow">RICHIAMO ATTIVO</span><h3>Chiudi gli occhi e spiegalo in 30 secondi</h3><p>Quando si usa? Quali sono le tre azioni essenziali? Come termina il gesto?</p><button onClick={()=>setReveal(!reveal)}>{reveal?'Nascondi risposta':'Mostra risposta da esame'}</button>{reveal&&<div className="exam-answer">{selected.exam}</div>}</div><div className="two-col"><div><h3>Tecnica</h3><ul>{selected.technique.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Errori da correggere</h3><ul className="errors">{selected.errors.map(x=><li key={x}>{x}</li>)}</ul><h3>Tattica</h3><p>{selected.tactics}</p></div></div></section></div>}
 {tab==="diagrammi"&&<div className="page"><div className="pagehead"><span className="eyebrow">LETTURA DEL GIOCO</span><h1>Leggi, nascondi, racconta.</h1><p>Segui la sequenza: chi ha la palla, cosa fa e quale vantaggio cerca.</p></div><div className="diagram-layout"><div className="court"><div className="paint"/><div className="circle"/><span className="d-player one">1<small>●</small></span><span className="d-player two">2</span><span className="pass-arrow">········➤</span><span className="cut-arrow">⌒➤</span><span className="basket">◉</span></div><div className="steps">{[["01","1 passa a 2","Passaggio sul lato destro: osserva palla, giocatori e direzione."],["02","1 taglia a canestro","Dopo il passaggio, 1 attacca lo spazio interno guardando la palla."],["03","2 legge e decide","Se il taglio è libero passa; se la difesa chiude, sceglie come mantenere il vantaggio."]].map(s=><article key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}<div className="challenge"><b>Prova orale</b><p>Guarda il diagramma per 20 secondi. Poi coprilo e racconta: <strong>chi → cosa → dove → perché</strong>.</p></div></div></div></div>}
 {tab==="esame"&&<div className="page"><div className="pagehead"><span className="eyebrow">MODALITÀ COMMISSIONE</span><h1>Simulatore d’esame</h1><p>Allenati nelle stesse quattro situazioni che troverai davanti alla commissione.</p></div><div className="exam-grid"><section className="exam-card featured"><div className="exam-label">PROVA SCRITTA · ARGOMENTO ESTRATTO</div><div className="timer">{minutes}:00</div><h2>Descrivi: {selected.title}</h2><p>Spiega obiettivo, tecnica, utilizzo tattico, conclusione ed errori principali.</p><textarea aria-label="Risposta scritta" placeholder="Scrivi qui senza consultare la scheda…"/><div className="actions"><button className="primary" onClick={()=>setRunning(!running)}>{running?'Pausa':'Avvia 30 minuti'}</button><button onClick={()=>{setSelected(topics[Math.floor(Math.random()*topics.length)]);setMinutes(30);setRunning(false)}}>Estrai altra domanda</button></div></section><section className="exam-card"><div className="exam-label">QUIZ RAPIDO · {quizIndex+1}/{quiz.length}</div><h2>{quiz[quizIndex].q}</h2><div className="answers">{quiz[quizIndex].a.map((a,i)=><button key={a} onClick={()=>choose(i)} className={answer===null?'':i===quiz[quizIndex].ok?'correct':i===answer?'wrong':''}>{a}</button>)}</div>{answer!==null&&<div className="quiz-result"><b>{answer===quiz[quizIndex].ok?'Corretto!':'Da ripassare'}</b><span>Punti: {points}</span><button onClick={()=>{setAnswer(null);setQuizIndex(i=>(i+1)%quiz.length)}}>Prossima →</button></div>}</section><section className="exam-card"><div className="exam-label">PROVA PRATICA</div><h2>Progressione: cambio di mano frontale</h2><ol><li>Obiettivo e prerequisiti</li><li>Attivazione e controllo</li><li>1c0: gesto tecnico</li><li>Lettura con difensore guidato</li><li>1c1 e trasferimento nel gioco</li></ol><div className="commission">Domanda commissione: <b>Quando scegli l’omologo invece dell’incrociato?</b></div></section><section className="exam-card"><div className="exam-label">BOOK TECNICO</div><h2>Difendi una tua scelta</h2><p>“Qual è l’obiettivo? Cosa osservi? Come aumenti la difficoltà? Quale errore correggi per primo?”</p><button className="outline" onClick={()=>{setSelected(topics[Math.floor(Math.random()*topics.length)]);setTab('fondamentali')}}>Estrai un fondamentale →</button></section></div></div>}
 <footer>FIP Memory Coach · Metodo VISTA · Contenuti rielaborati dalle dispense CNA caricate</footer></main>
}
